### ISSUE TITLE
IAD command with multiple measure without using rxt file

### ISSUE THREAD

**Issue by RashidLadj** [scottprahl/iad#10]
Hello, is there a way to execute the iad command with N r and N t without going through an rxt file like:
IAD -B 8.1 -S 1 -1 "60.0 16.9 12.4 9.0 97.1" -2 "60.0 16.9 0.0 9.0 97.1" -d 0.5 -d 1.25 -N 0.9998047800454378 -N 1.5048941657272727 -r 0.830258748 -r '17. 44.6352'

![image](https://user-images.githubusercontent.com/59792800/201893536-de754eec-4a62-4743-90bd-ec1f0a45c18f.png)

**Comment by scottprahl** [comment]
@RashidLadj sorry for the year long wait.  I did not see your comment.  The answer is yes, but I don't really follow your command.  This much seems fine

```
    iad -B 8.1 -S 1 
```

The wall reflection should be between zero and one so 97.1 becomes 0.971.  I also fixed changed `-d 1.25` to your slide thickness `-D 1.25`.

```
    iad -B 8.1 -S 1 -1 "60.0 16.9 12.4 9.0 0.971" -2 "60.0 16.9 0.0 9.0 0.971" -d 0.5 -D 1.25
```
The rest should be something like
```
    iad -B 8.1 -S 1 -1 "60.0 16.9 12.4 9.0 0.971" -2 "60.0 16.9 0.0 9.0 0.971" -d 0.5 -D 1.25 -n 1.4 -N 1.5 -r 0.83 -t 0.05
```
but your last four command line arguments are confused.
