### ISSUE TITLE
Negative anisotropy factor input?

### ISSUE THREAD

**Issue by Jaasim99** [scottprahl/iad#15]
When attempting to input a negative value of 'g' in the command line input, the negative sign is interpreted as the beginning of a parameter.
![test](https://github.com/scottprahl/iad/assets/169877740/fd7c9e4a-0bbe-4672-acb0-0b93cd87601e)

**Comment by scottprahl** [comment]
You need to put the negative value in quotes. 

```bash
iad -A 0.01 -g '-0.2' -d 1 -j 1 -z
```
gives

```
##wave  M_R     fit     M_T     fit    mu_a    mu_s'     g
# [nm] [---]   [---]   [---]   [---]   1/mm    1/mm    [---]
 0     0.0000  0.3421  0.0000  0.6426  0.0100  1.0000 -0.2000
```

**Comment by Jaasim99** [comment]
Thank you, that was it. I couldn't find any example in the manual which made use of negative g, hence it had me perplexed.
