### ISSUE TITLE
Can't execute IAD on a raspberry pi: "unknown option '�'"

### ISSUE THREAD

**Issue by eduardosprp** [scottprahl/iad#3]
Good afternoon. I am trying to execute IAD on a Raspberry Pi 3 Model B+ running Raspbian, I've followed the instructions for installation but whenever I try to run the program it always outputs 
"unknown option '�'", followed by a description of the program. I've tried executing the program on multiple files, and tried some of the options presented in the aforementioned description, to no avail.

Here is a copy of my input and the corresponding output. The unknown symbol '�' is displayed in the output, by the way. It is not a formatting error:

pi@raspberrypi:~/Downloads/iad-3-11-1 $ iad test/basic-A.rxt
unknown option '�'
iad 3-11-1 (28 Mar 2019)

iad finds optical properties from measurements

Usage:  iad [options] input

Options:
  -1 '# # # # #'   reflection sphere parameters 
  -2 '# # # # #'   transmission sphere parameters 

...and it goes on

Could you please tell me how do I fix this? Thanks in advance.

**Comment by scottprahl** [comment]
Interesting.  I have never tried to compile `iad` on a Raspberry Pi before.  Should not be a problem though.  It would help if you verified that version 3-11-3

https://github.com/scottprahl/iad/releases/tag/v3.11.3

gives the same result. If so, I will dig out my RPi and see what is going on.

**Comment by eduardosprp** [comment]
Hello. First of all, thanks for the quick answer!

I've compiled version 3.11.3 and running ./iad test/basic-A.rxt. The result is the same as before:

pi@raspberrypi:~/Downloads/iad-3.11.3 $ ./iad test/basic-A.rxt
unknown option '�'
iad 3-11-3 (21 Aug 2019)

iad finds optical properties from measurements

Usage:  iad [options] input

Options:
  -1 '# # # # #'   reflection sphere parameters 
... It goes on

**Comment by scottprahl** [comment]
During compiling, do you get any warnings?  There should be none.

**Comment by eduardosprp** [comment]
No, there weren't any. Just to be sure, I tried compiling it once more, and this is what I got:

pi@raspberrypi:~/Downloads/iad-3.11.3 $ sudo make install
cd src ; make ad
make[1]: Entering directory '/home/pi/Downloads/iad-3.11.3/src'
./version.pl 
cc -c -o version.o version.c 	
cc -o ad nr_zbrak.o ad_bound.o ad_doubl.o ad_frsnl.o ad_globl.o ad_matrx.o ad_phase.o ad_prime.o ad_radau.o ad_start.o ad_cone.o ad_layers.o nr_amoeb.o nr_amotr.o nr_brent.o nr_gaulg.o nr_mnbrk.o nr_rtsaf.o nr_util.o mc_lost.o nr_hj.o nr_zbrent.o ad_main.o mygetopt.o version.o -lm
make[1]: Leaving directory '/home/pi/Downloads/iad-3.11.3/src'
cp src/ad ad
cd src ; make iad
make[1]: Entering directory '/home/pi/Downloads/iad-3.11.3/src'
./version.pl 
cc -c -o version.o version.c 
cc -o iad nr_zbrak.o ad_bound.o ad_doubl.o ad_frsnl.o ad_globl.o ad_matrx.o ad_phase.o ad_prime.o ad_radau.o ad_start.o ad_cone.o ad_layers.o iad_util.o iad_calc.o iad_find.o iad_pub.o iad_io.o nr_amoeb.o nr_amotr.o nr_brent.o nr_gaulg.o nr_mnbrk.o nr_rtsaf.o nr_util.o mc_lost.o nr_hj.o nr_zbrent.o iad_main.o mygetopt.o version.o -lm
make[1]: Leaving directory '/home/pi/Downloads/iad-3.11.3/src'
cp src/iad iad
mkdir -p /usr/local/bin
rm -f /usr/local/bin/ad
cp ad  /usr/local/bin
rm -f /usr/local/bin/iad
cp -f iad /usr/local/bin

When executed again, however, the same error message is displayed:

pi@raspberrypi:~/Downloads/iad-3.11.3 $ iad test/basic-A.rxt
unknown option '�'
iad 3-11-3 (21 Aug 2019)

iad finds optical properties from measurements

Usage:  iad [options] input

Options:
  -1 '# # # # #'   reflection sphere parameters 
  -2 '# # # # #'   transmission sphere parameters 
... It goes on

If I try running iad on sudo the same output is given, by the way.

**Comment by eduardosprp** [comment]
Oh, I've just now tried changing the locale configuration of Raspbian from Portuguese - Brazil to English - US. The unknown character is revealed to be a Y with an umlaut:

pi@raspberrypi:~/Downloads/iad-3.11.3 $ iad test/basic-A.rxt
unknown option 'ÿ'
iad 3-11-3 (21 Aug 2019)

iad finds optical properties from measurements

Usage:  iad [options] input

Options:
  -1 '# # # # #'   reflection sphere parameters 
... and it goes on

Still no idea what is causing it, though.

**Comment by scottprahl** [comment]
I just verified the problem on RPi.  The problem is not related to locale.  My guess right now is that the complier is handling character strings slightly differently.  Will investigate more later today.

**Comment by eduardosprp** [comment]
Ok, please post what you find then. Thank you for your patience!

**Comment by scottprahl** [comment]
Figured it out.  RPi needs the flag -fchar-signed to compile correctly.  Tested on my RPi and it works.  Slowly.

I released a new version with this fix.
