### ISSUE TITLE
Calculate mua and mus with mus as input

### ISSUE THREAD

**Issue by Yijing-KCL** [scottprahl/iad#4]
Dear IAD team,
We are using the IAD package for calculating the reduced scattering and absorption of excised tissue from single integrating sphere measurements: total reflectance and total transmission. 
We wonder if the present version of IAD package is able to include a pre-estimated reduced scattering spectrum in the input .txt file (with headers as integrating sphere parameters).
Thank you in advance! Looking to your reply!

**Comment by scottprahl** [comment]
What you ask is reasonable, but arbitrary mus/mus' values withn the input `.rxt` file is specialized.  

In the general case, you would have to write a shell script to iterate `iad` over measurements at each wavelength.  For a single analysis or two, this what I would probably do.

If your **scattering model is a simple power law**, then you are in luck.  You use the `-F` command line option for `iad` when processing your file

    iad −F ’P 500 1.5 −1.3’ file.rxt

should constrain mus=1.5*(lambda/500)**(-1.3) where lambda is read as the first column in the `.rxt` file.  Alternatively, 

    iad −F ’R 500 1.5 −1.3’ file.rxt

will constrain the reduced scattering coefficient instead.

If this doesn't work as expected, please create a new issue and I will look into it.

**Comment by Yijing-KCL** [comment]
Thank you for your prompt reply! Very helpful!

Will give a go and let you know the outcome!

Best,

Yijing
------------------------------------------
Dr.-Ing. Yijing Xie, (she, her)
Research Associate
School of Biomedical Engineering and Imaging Sciences,
King’s College London

9th floor, Becket House
1 Lambeth Palace Road
London SE1 7EU







On 28 Jul 2020, at 17:57, Scott Prahl <notifications@github.com<mailto:notifications@github.com>> wrote:



What you ask is reasonable, but arbitrary mus/mus' values withn the input .rxt file is specialized.

In the general case, you would have to write a shell script to iterate iad over measurements at each wavelength. For a single analysis or two, this what I would probably do.

If your scattering model is a simple power law, then you are in luck. You use the -F command line option for iad when processing your file

iad −F ’P 500 1.5 −1.3’ file.rxt


should constrain mus=1.5*(lambda/500)**(-1.3) where lambda is read as the first column in the .rxt file. Alternatively,

iad −F ’R 500 1.5 −1.3’ file.rxt


will constrain the reduced scattering coefficient instead.

If this doesn't work as expected, please create a new issue and I will look into it.

**Comment by udaya24** [comment]
@scottprahl In continuation with the above question by Yijing, I would like to do forward calculations using  Adding-doubling method. It's surprising for me that, I could not able to locate the input file format to provide mua, mus and g as an input to get reflectance and transmittance. But, I could able to see many examples of how to give input file for inverse calculations. Would you please kindly add the examples for forward calculation as well would be great.

**Comment by waityouwait** [comment]
你好，可以从哪里看到具体的例子呢，作为刚刚入门的新手，麻烦前沿学者给与指点迷津

**Comment by scottprahl** [comment]
I know this is super late --- don't think I ever saw your comments sorry.

@udaya24 and @waityouwait if you do `iad -h` you will learn what you need.  In particular the `-z` allows one to do forward calculations.

```
  iad -z -a 0.9 -b 1 -i 45  Forward calc assuming 45 degree incidence
```
