### ISSUE TITLE
RT_Layers Producing 0s

### ISSUE THREAD

**Issue by Grieverheart** [scottprahl/iad#6]
Weird (I think) bug where RT_Layers produces 0s if called first. You can test this by e.g. going to ad_layers_test.c and commenting out the first ez_RT. The RT_Layers after that will produce 0s instead of the correct reflectance and transmitance values. Tested with both Clang and GCC.

**Comment by scottprahl** [comment]
Thanks for the bug report!  Yes, there was a missing initialization.  Released a new version that fixes the bug.
