### ISSUE TITLE
Hello, Professor, can I use collimated LED light as the light source of double integrating sphere experiment

### ISSUE THREAD

**Issue by fengzefeng** [scottprahl/iad#8]
Hello, Professor, can I use collimated LED light as the light source of double integrating sphere experiment？Because the integrating sphere in our laboratory is very large, we need large optical power. The power of He Ne laser may not be enough, and we also don't have He Ne laser.

**Comment by scottprahl** [comment]
Sorry for the very belated reply.  I did not see your comment @fengzefeng 

The answer is that you can use an LED light source, but you must be careful to account for light that hits the sphere wall first (for a reflection measurement).  A total transmission measurement should work well.

You will never be able to do a good unscattered transmission measurement with an LED though.  So at best you can determine two optical parameters.
